### ISSUE TITLE
Tracking Issue: Complete TypeScript Migration

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#983]
### Context

Currently, the design-system is a mix of Typescript and JavaScript. The latter prevents us e.g. from publishing types. In this issue we want to track the migration process and make sure everything is typed correctly.

If you'd like to work on a component, please comment on which one and we will add you to the list.

## Components

- [x] Accordion
- [x] Alert
- [x] Avatar
- [x] Badge
- [x] BaseButton
- [x] BaseCheckbox
- [x] BaseLink
- [x] BaseRadio
- [x] Box
- [x] Breadcrumbs
- [x] Button
- [x] Card
- [x] CarouselInput @gu-stav 
- [x] Checkbox @simotae14 
- [x] Combobox
- [x] DatePicker
- [x] DateTimePicker
- [x] Dialog @Minecraftschurli 
- [x] DismissableLayer 
- [x] Divider @gu-stav 
- [x] EmptyStateLayout @gu-stav 
- [x] Field
- [x] Flex
- [x] FocusTrap
- [x] Grid @christiancp100 
- [x] Icon
- [x] IconButton
- [x] JSONInput
- [x] KeyboardNavigable
- [x] Layout @gu-stav 
- [x] Link
- [x] LinkButton
- [x] LiveRegions
- [x] Loader
- [x] Main @gu-stav 
- [x] MainNav @gu-stav 
- [x] ModalLayout @gu-stav 
- [x] NumberInput @Minecraftschurli 
- [x] Pagination @gu-stav 
- [x] Popover
- [x] Portal
- [x] ProgressBar @gu-stav 
- [x] Radio @gu-stav 
- [x] RawTable
- [x] Searchbar
- [x] Select
- [x] SimpleMenu @Minecraftschurli 
- [x] Stack
- [x] Status
- [x] SubNav @gu-stav 
- [x] Switch @Minecraftschurli 
- [x] Table
- [x] Tabs @markkaylor 
- [x] Tag
- [x] Textarea @gu-stav 
- [x] TextButton
- [x] TextInput
- [x] ThemeProvider
- [x] TimePicker
- [x] ToggleCheckbox @markkaylor 
- [x] ToggleInput @markkaylor 
- [x] Tooltip
- [x] Typography
- [x] VisuallyHidden

### v2: located in `src/v2`

- [x] Breadcrumbs @simotae14
- [x] Link
- [x] LinkButton
- [x] MainNav @Minecraftschurli 
- [x] Pagination @gu-stav 
- [x] SimpleMenu
- [x] SubNav @Minecraftschurli 

## Themes ✅ 

- [x] darktheme and lighttheme

## Hooks ✅ 

- [x] useComposeRefs
- [x] useControllableState
- [x] useElementOnScreen
- [x] useId
- [x] useIntersection
- [x] useLockScroll
- [x] usePrevious
- [x] useResizeObserver

### Components
- [x] Collection
- [x] Combobox
- [x] Select

### Hooks

- [x] useCollator
- [x] useFilter
- [x] usePrev

**Comment by markkaylor** [comment]
I can do ToggleInput next week

**Comment by simotae14** [comment]
Same here, I can do Checkbox during this sprint

**Comment by christiancp100** [comment]
I can work on Grid, or any other actually

**Comment by markkaylor** [comment]
I'll do Tabs

**Comment by HichamELBSI** [comment]
I'll take the SubNav component! 😁

**Comment by markkaylor** [comment]
ToggleCheckbox is marked as done but I still see it as JS component: https://github.com/strapi/design-system/tree/main/packages/strapi-design-system/src/ToggleCheckbox

If nobody is working on it I'd like to pick it up

**Comment by Minecraftschurli** [comment]
done with NumberInput gonna continue with Dialog

**Comment by Minecraftschurli** [comment]
another one done gonna do Searchbar next

**Comment by Minecraftschurli** [comment]
while I'm at it I also did Switch

**Comment by joshuaellis** [comment]
Nope, once we've got the rest of the PRs merged we can start doing some TS experimental releases and test against our cloud repo for better insight into affects in the community and whether or not this needs to be a breaking change.

**Comment by Minecraftschurli** [comment]
Why were #1054
, #1055
 and #1057 closed without merging?

**Comment by joshuaellis** [comment]
I think that was automatic when i deleted a branch 🤔  we should reopen those – thanks for the nudge 👍🏼

**Comment by joshuaellis** [comment]
I'm away for a week, Table is open to someone else if they feel like it 👍🏼

**Comment by Minecraftschurli** [comment]
I'll take a look

**Comment by gu-stav** [comment]
@HichamELBSI Are you working on `Subnav`? Otherwise I'd take it over :)

**Comment by gu-stav** [comment]
The migration is done ✨ Thanks to everyone involved. Special shoutouts to @Minecraftschurli for the tremendous help!
